package com.outreach.interviews.google.maps;

import java.io.IOException;

import org.joda.time.DateTime;
import org.joda.time.ReadableInstant;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.maps.GeocodingApi;
import com.google.maps.errors.ApiException;
import com.google.maps.model.GeocodingResult;

/**
 * Longitude and Latitude generated by {@link https://www.latlong.net/}
 * @author Patrique Legault
 *
 */
public class DirectionsRequest
{
	private final OutreachGeoContext outreachGeoContext;

	Logger log = LoggerFactory.getLogger(this.getClass());

	public DirectionsRequest(OutreachGeoContext outreachGeoContext) {
		this.outreachGeoContext = outreachGeoContext;
	}

	public void getDirections() throws ApiException, InterruptedException, IOException {
		
		GeocodingResult[] results =  GeocodingApi.geocode(outreachGeoContext.getGeoApiContext(),
				"1600 Amphitheatre Parkway Mountain View, CA 94043").await();
		
		Gson gson = new GsonBuilder().setPrettyPrinting().create();
		
		System.out.println(gson.toJson(results[0].addressComponents));
	}

	public static ReadableInstant getTime() {
		return new DateTime();
	}
}
